WIP: fix tty
sigstore/gitsign pull request #31
Opened 2022-05-15 17:25 UTC by benmoss

#### Summary
Fixes TTY so we can potentially use the full device mode flow. WIP since I don't actually know how to wire things up correctly!

I get:
```
git commit --allow-empty --message="Signed commit"
Generating ephemeral keys...
Retrieving signed certificate...
error opening browser: exit status 3
Go to the following link in a browser:

         https://oauth2.sigstore.dev/auth/auth?access_type=online&client_id=sigstore&code_challenge=eWoZR6hFhWQR1T915CaQmv0lnpaTd-JVNHnf5_n-DJA&code_challenge_method=S256&nonce=29D6uYWOJa6ZkWcB3C2QBlCx36g&redirect_uri=http%3A%2F%2Flocalhost%3A36555%2Fauth%2Fcallback&response_type=code&scope=openid+email&state=29D6uTrvll8Bxa2noFXAogMwRjp
Enter verification code: error getting signer: getting key from Fulcio: retrieving cert: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid or expired code parameter."}
failed to get identity: getting key from Fulcio: retrieving cert: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid or expired code parameter."}
error: gpg failed to sign the data
fatal: failed to write commit object
```

#### Ticket Link

Fixes #20

#### Release Note

```release-note

```

2022-05-15 17:35 UTC, benmoss commented
By overriding `os.Stdout` as well I get all the way to:

```
❯ git commit --allow-empty --message="Signed commit"
Generating ephemeral keys...
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code RJPC-JFGP in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=RJPC-JKHP
Code will be valid for 300 seconds
Token received!
Successfully verified SCT...
[GNUPG:] BEGIN_SIGNING
[GNUPG:] SIG_CREATED D 19 9 00 1622636040 8ddd6033adada15cb30653702fb6eccc8b74ae6e7c
error: gpg failed to sign the data
fatal: failed to write commit object
```

2022-05-17 13:07 UTC, wlynch requested changes
Thanks for taking a look at this! 😄

2022-05-17 14:02 UTC, imjasonh commented on internal/fulcio/fulcio.go
> +	authFlow := ""
+1, this is a great reason not to depend on cosign's behavior, since it has different expectations about how it's invoked.

2022-05-18 13:41 UTC, benmoss commented on main.go
> +	os.Stdout = stderr
Yeah, this was just to be able to surface the cosign messages at all, we'll likely need to first make changes there to have a logging interface to have this work in any kind of sane way.

2022-06-17 13:38 UTC, closed without merging