Added environment variable for OIDC Redirect URL
sigstore/gitsign pull request #39
Opened 2022-05-19 17:48 UTC by Boolman

Allow for specifying the OIDC Redirect URL so we can specify a predictable redirect

2022-05-20 08:46 UTC, cpanato submitted a review, later dismissed

2022-05-20 10:56 UTC, wlynch requested changes
Thanks for adding this! One small tweak, but otherwise looks good.

2022-05-20 10:56 UTC, wlynch commented on internal/fulcio/fulcio.go
> +		OIDCRedirectURL: envOrValue("GITSIGN_OIDC_REDIRECT_URL", "http://localhost:5000/auth/callback"),
```suggestion
		OIDCRedirectURL: os.Getenv("GITSIGN_OIDC_REDIRECT_URL"),
```

Redirect URL is a bit unique in that there's already code for handling defaults - which is also smart about auto-selecting an unused port. The other environment variables are defaults that are set by cosign (though @imjasonh perhaps we should also move these up to sigstore/sigstore 🤔 )

https://github.com/sigstore/sigstore/blob/5095b189ff654aea7e4964692a082855714e83b5/pkg/oauth/oidc/interactive.go#L56

2022-05-23 08:49 UTC, wlynch approved these changes

2022-05-23 08:50 UTC, merged